from . import capy_product
from . import capy_customer
from . import capy_supplier
from . import capy_stock
from . import capy_order
from . import capy_order_line
from . import capy_invoice
from . import capy_payment
from . import capy_purchase_order
from . import capy_purchase_order_line
from . import capy_employee
from . import capy_expense
from . import capy_lead
from . import capy_approval